name: HeroMagic
main: com.HeroCraft.Dgco.HeroMagic.HeroMagic
version: 0.9
author: Dgco, Sp1rit
database: true
description: >
             Casts Stuff
commands:
  cast:
    description: Casts a spell.
    usage: |
           /<command> <spell> [params]
           Example: /<command>